image:
  file: .gitpod.Dockerfile

tasks:
- name: Start Couchbase
  command:  cd /opt/couchbase/ && ./start-cb.sh
- name: Start app
  init: cd src/Org.Quickstart.API 
  command:  dotnet build && dotnet run 

# exposed ports
ports:
- port: 5000
  onOpen: open-preview
- port: 5001
  onOpen: open-preview 
- port: 8091
  onOpen: open-browser
- port: 8092-10000
  onOpen: ignore
- port: 4369
  onOpen: ignore

vscode:
  extensions:
    - muhammad-sammy.csharp